version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.4
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"  # cổng mặc định của Logstash
    depends_on:
      - elasticsearch

  app:
    image: openjdk:17-jdk
    container_name: springboot-app
    volumes:
      - ./your-spring-boot-app.jar:/app/your-spring-boot-app.jar
    command: ["java", "-jar", "/app/your-spring-boot-app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - kibana
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml  # Mapping file cấu hình
    ports:
      - "9090:9090"  # Mở cổng 9090 cho Prometheus
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Mở cổng 3000 cho Grafana

volumes:
  esdata:
